version: '3.8'

services:
  web:
    build: .
    command: python /dockerprojects/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/dockerprojects
    environment:
      - SECRET_KEY=e^!h7g*62$$h+798ba2ngs*%q21-2j0z=y+*tro2ybxv7#18316
      - DEBUG=1
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=love2life4ever
